scalar JSON
scalar JSONObject

interface EntityMetadata {
  name: String!
  annotations: JSONObject!
  annotation(name: String!): JSON
  labels: JSONObject!
  label(name: String!): JSON
  uid: String!
  etag: String!
  generation: Int!
}

type ComponentMetadata implements EntityMetadata {
  name: String!
  annotations: JSONObject!
  annotation(name: String!): JSON
  labels: JSONObject!
  label(name: String!): JSON
  uid: String!
  etag: String!
  generation: Int!
  relationships: String!
}

type TemplateMetadata implements EntityMetadata {
  name: String!
  annotations: JSONObject!
  annotation(name: String!): JSON
  labels: JSONObject!
  label(name: String!): JSON
  uid: String!
  etag: String!
  generation: Int!
  updatedBy: String!
}

type DefaultEntityMetadata implements EntityMetadata {
  name: String!
  annotations: JSONObject!
  annotation(name: String!): JSON
  labels: JSONObject!
  label(name: String!): JSON
  uid: String!
  etag: String!
  generation: Int!
}

type CatalogEntity {
  apiVersion: String!
  kind: String!
  metadata: EntityMetadata!
}

type CatalogQuery {
  list: [CatalogEntity!]!
}

type Query {
  catalog: CatalogQuery!
}
