scalar JSON
scalar JSONObject

type EntityMetadata {
  name: String!
  namespace: String!
  annotations: JSONObject!
  annotation(name: String!): JSON
  labels: JSONObject!
  label(name: String!): JSON
  uid: String!
  etag: String!
  generation: Int!
}

type CatalogEntity {
  apiVersion: String!
  kind: String!
  metadata: EntityMetadata!
}

type CatalogQuery {
  list: [CatalogEntity!]!
}

type Query {
  catalog: CatalogQuery!
}
