apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-cli-module-scaffolder
  title: '@backstage/cli-module-scaffolder'
  description: CLI module for listing and executing software templates
spec:
  lifecycle: experimental
  type: backstage-cli-module
  owner: tooling-maintainers
