approvedGitRepositories: []

compressionLevel: mixed

enableGlobalCache: true

enableScripts: false

httpTimeout: 300000

nodeLinker: node-modules

npmMinimalAgeGate: 1d

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: .yarn/releases/yarn-4.18.0.cjs
