approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

httpTimeout: 300000

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
