#Setup build image
FROM node:lts-buster AS build-env

#Set container filesystem to /build (and create folder if it doesnt exist)
WORKDIR /build

#Copy files to container file system.
COPY ./ ./src

#Set workdir to current project folder
WORKDIR /build/src

#Run yarn install
RUN yarn install
RUN yarn bundle


FROM nginx:mainline AS release

RUN apt-get update && apt-get -y install jq && rm -rf /var/lib/apt/lists/*

# Get application files from build-env image
COPY --from=build-env /build/src/packages/app/dist /usr/share/nginx/html

# Get nginx config files from local host
COPY docker/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY docker/run.sh /usr/local/bin/run.sh
CMD run.sh

ENV PORT 80
