export const SNACKBAR_OPEN_DEFAULT = 'SNACKBAR_OPEN_DEFAULT';
export const SNACKBAR_OPEN_SUCCESS = 'SNACKBAR_OPEN_SUCCESS';
export const SNACKBAR_OPEN_ERROR = 'SNACKBAR_OPEN_ERROR';
export const SNACKBAR_CLOSE = 'SNACKBAR_CLOSE';
