apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-rjsf-bui-theme
  title: '@backstage/rjsf-bui-theme'
spec:
  lifecycle: experimental
  type: backstage-web-library
  owner: framework-maintainers
