export const mockGitHubData = [
  {
    url: 'https://api.github.com/repos/backstage/backstage/issues/7664',
    repository_url: 'https://api.github.com/repos/backstage/backstage',
    labels_url:
      'https://api.github.com/repos/backstage/backstage/issues/7664/labels{/name}',
    comments_url:
      'https://api.github.com/repos/backstage/backstage/issues/7664/comments',
    events_url:
      'https://api.github.com/repos/backstage/backstage/issues/7664/events',
    html_url: 'https://github.com/backstage/backstage/issues/7664',
    id: 1029405967,
    node_id: 'I_kwDODhKIWM49W30P',
    number: 7664,
    title: 'Sections from Tech Radar disappear when there are too many entries',
    user: {
      login: 'julioz',
      id: 1541701,
      node_id: 'MDQ6VXNlcjE1NDE3MDE=',
      avatar_url: 'https://avatars.githubusercontent.com/u/1541701?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/julioz',
      html_url: 'https://github.com/julioz',
      followers_url: 'https://api.github.com/users/julioz/followers',
      following_url:
        'https://api.github.com/users/julioz/following{/other_user}',
      gists_url: 'https://api.github.com/users/julioz/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/julioz/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/julioz/subscriptions',
      organizations_url: 'https://api.github.com/users/julioz/orgs',
      repos_url: 'https://api.github.com/users/julioz/repos',
      events_url: 'https://api.github.com/users/julioz/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/julioz/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 1807372872,
        node_id: 'MDU6TGFiZWwxODA3MzcyODcy',
        url: 'https://api.github.com/repos/backstage/backstage/labels/bug',
        name: 'bug',
        color: 'd73a4a',
        default: true,
        description: "Something isn't working",
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 1,
    created_at: '2021-10-18T17:36:28Z',
    updated_at: '2021-10-18T21:25:08Z',
    closed_at: null,
    author_association: 'CONTRIBUTOR',
    active_lock_reason: null,
    body: "<!--- Provide a general summary of the issue in the Title above -->\r\n\r\n## Expected Behavior\r\n\r\n<!--- Tell us what should happen -->\r\n\r\nAs seen in the [demo](https://demo.backstage.io/tech-radar), when the tech radar is rendered, we expect four sections to surround the drawing.\r\n\r\n## Current Behavior\r\n\r\n<!--- Tell us what happens instead of the expected behavior -->\r\n\r\nWhen there are too many entries to the radar, some of the sections disappear. This must be a rendering bug, since using the 'search' functionality to filter out entries brings the sections back.\r\n\r\nChanging the `width` and `height` properties of the React component does not help.\r\n\r\nYou can plug-in the [ThoughtWorks public radar data](https://docs.google.com/spreadsheets/d/18A7oDuavlh89rAmqcaXpqle8QLqIvlAkoEUxcObzuUM/edit#gid=1985253373) to reproduce the bug.\r\n\r\n## Possible Solution\r\n\r\n<!--- Not obligatory, but suggest a fix/reason for the bug, -->\r\n<!--- or ideas as to the implementation of the addition or change -->\r\n\r\n## Steps to Reproduce\r\n\r\n<!--- Provide a link to a live example, or an unambiguous set of steps to -->\r\n<!--- reproduce this bug. Include code or configuration to reproduce, if relevant -->\r\n\r\n1. Include 100+ entries distributed across the radar data\r\n2. Observe\r\n\r\n## Context\r\n\r\n<!--- How has this issue affected you? What are you trying to accomplish? -->\r\n<!--- Providing context (e.g. links to configuration settings, -->\r\n<!--- stack trace or log data) helps us come up with a solution that is most useful in the real world -->\r\n\r\n## Your Environment\r\n\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n\r\n<!-- ProTip: You can use `yarn backstage-cli info` command in your Backstage App for this section. -->\r\n\r\n- NodeJS Version (v14): v16.8.0\r\n- Operating System and Version (e.g. Ubuntu 14.04): MacOS Big Sur\r\n- Browser Information: Chrome Version 94.0.4606.81\r\n",
    reactions: {
      url: 'https://api.github.com/repos/backstage/backstage/issues/7664/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      'https://api.github.com/repos/backstage/backstage/issues/7664/timeline',
    performed_via_github_app: null,
  },
  {
    url: 'https://api.github.com/repos/backstage/backstage/issues/7663',
    repository_url: 'https://api.github.com/repos/backstage/backstage',
    labels_url:
      'https://api.github.com/repos/backstage/backstage/issues/7663/labels{/name}',
    comments_url:
      'https://api.github.com/repos/backstage/backstage/issues/7663/comments',
    events_url:
      'https://api.github.com/repos/backstage/backstage/issues/7663/events',
    html_url: 'https://github.com/backstage/backstage/pull/7663',
    id: 1029394083,
    node_id: 'PR_kwDODhKIWM4tV0yg',
    number: 7663,
    title: '[Azure DevOps Plugin] Fix the plugin import in the readme',
    user: {
      login: 'Abhith',
      id: 7039457,
      node_id: 'MDQ6VXNlcjcwMzk0NTc=',
      avatar_url: 'https://avatars.githubusercontent.com/u/7039457?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Abhith',
      html_url: 'https://github.com/Abhith',
      followers_url: 'https://api.github.com/users/Abhith/followers',
      following_url:
        'https://api.github.com/users/Abhith/following{/other_user}',
      gists_url: 'https://api.github.com/users/Abhith/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/Abhith/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Abhith/subscriptions',
      organizations_url: 'https://api.github.com/users/Abhith/orgs',
      repos_url: 'https://api.github.com/users/Abhith/repos',
      events_url: 'https://api.github.com/users/Abhith/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/Abhith/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 2,
    created_at: '2021-10-18T17:22:11Z',
    updated_at: '2021-10-18T18:07:45Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    pull_request: {
      url: 'https://api.github.com/repos/backstage/backstage/pulls/7663',
      html_url: 'https://github.com/backstage/backstage/pull/7663',
      diff_url: 'https://github.com/backstage/backstage/pull/7663.diff',
      patch_url: 'https://github.com/backstage/backstage/pull/7663.patch',
    },
    body: "<!-- Please describe what you added, and add a screenshot if possible.\r\n     That makes it easier to understand the change so we can :shipit: faster. -->\r\n\r\nPreviously, we were asking to create `../plugins/**azure-devops**.ts` and import from `'./plugins/**azuredevops**'`, which is corrected.\r\n\r\n#### :heavy_check_mark: Checklist\r\n\r\n<!--- Please include the following in your Pull Request when applicable: -->\r\n\r\n- [ ] A changeset describing the change and affected packages. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#creating-changesets))\r\n- [x] Added or updated documentation\r\n- [ ] Tests for new functionality and regression tests for bug fixes\r\n- [ ] Screenshots attached (for UI changes)\r\n- [x] All your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))\r\n",
    reactions: {
      url: 'https://api.github.com/repos/backstage/backstage/issues/7663/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      'https://api.github.com/repos/backstage/backstage/issues/7663/timeline',
    performed_via_github_app: null,
  },
  {
    url: 'https://api.github.com/repos/backstage/backstage/issues/7661',
    repository_url: 'https://api.github.com/repos/backstage/backstage',
    labels_url:
      'https://api.github.com/repos/backstage/backstage/issues/7661/labels{/name}',
    comments_url:
      'https://api.github.com/repos/backstage/backstage/issues/7661/comments',
    events_url:
      'https://api.github.com/repos/backstage/backstage/issues/7661/events',
    html_url: 'https://github.com/backstage/backstage/issues/7661',
    id: 1029297513,
    node_id: 'I_kwDODhKIWM49WdVp',
    number: 7661,
    title:
      'scaffolder.backstage.io/v1beta3 - Register Issue using replaceProcessors ',
    user: {
      login: 'regicsolutions',
      id: 6157895,
      node_id: 'MDQ6VXNlcjYxNTc4OTU=',
      avatar_url: 'https://avatars.githubusercontent.com/u/6157895?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/regicsolutions',
      html_url: 'https://github.com/regicsolutions',
      followers_url: 'https://api.github.com/users/regicsolutions/followers',
      following_url:
        'https://api.github.com/users/regicsolutions/following{/other_user}',
      gists_url: 'https://api.github.com/users/regicsolutions/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/regicsolutions/starred{/owner}{/repo}',
      subscriptions_url:
        'https://api.github.com/users/regicsolutions/subscriptions',
      organizations_url: 'https://api.github.com/users/regicsolutions/orgs',
      repos_url: 'https://api.github.com/users/regicsolutions/repos',
      events_url:
        'https://api.github.com/users/regicsolutions/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/regicsolutions/received_events',
      type: 'User',
      site_admin: false,
    },
    labels: [
      {
        id: 1807372872,
        node_id: 'MDU6TGFiZWwxODA3MzcyODcy',
        url: 'https://api.github.com/repos/backstage/backstage/labels/bug',
        name: 'bug',
        color: 'd73a4a',
        default: true,
        description: "Something isn't working",
      },
    ],
    state: 'open',
    locked: false,
    assignee: null,
    assignees: [],
    milestone: null,
    comments: 0,
    created_at: '2021-10-18T15:47:59Z',
    updated_at: '2021-10-18T15:49:51Z',
    closed_at: null,
    author_association: 'NONE',
    active_lock_reason: null,
    body: "<!--- Provide a general summary of the issue in the Title above -->\r\n\r\n## Expected Behavior\r\n\r\nI should be able to register a component using the catalog:register action as such:\r\n\r\n```\r\nsteps:\r\n    - id: publish\r\n      name: Create a Repo\r\n      action: publish:bitbucket\r\n      input:\r\n        repoUrl: ${{ parameters.repoUrl }}\r\n\r\n    - id: register\r\n      name: Register\r\n      action: catalog:register\r\n      input:\r\n        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}\r\n        catalogInfoPath: /catalog-info.yaml\r\n        \r\n  output:\r\n    remoteUrl: ${{ steps.publish.output.remoteUrl }}\r\n    entityRef: ${{ steps.register.output.entityRef }}\r\n      \r\n```\r\n\r\n## Current Behavior\r\n\r\nWhen using replaceProcessors as such:\r\n\r\n```\r\nimport {\r\n    AnnotateLocationEntityProcessor,\r\n    BitbucketDiscoveryProcessor,\r\n    CatalogBuilder,\r\n    FileReaderProcessor,\r\n    LocationEntityProcessor,\r\n    UrlReaderProcessor,\r\n  } from '@backstage/plugin-catalog-backend';\r\n  import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';\r\n  import { Router } from 'express';\r\n  import { PluginEnvironment } from '../types';\r\n  import { ScmIntegrations } from '@backstage/integration';\r\n  import { LdapOrgReaderProcessor } from '@backstage/plugin-catalog-backend-module-ldap';\r\n  import { customBitbucketRepositoryParser } from './catalog/customBitbucketRepositoryParser';\r\n  import { customGroupTransformer, customUserTransformer } from './catalog/customLDAPTransformer';\r\n  \r\n  export default async function createPlugin(\r\n    env: PluginEnvironment,\r\n  ): Promise<Router> {\r\n    const integrations = ScmIntegrations.fromConfig(env.config);\r\n    const builder = await CatalogBuilder.create(env);\r\n  \r\n    builder.replaceProcessors([\r\n      new FileReaderProcessor(),\r\n      BitbucketDiscoveryProcessor.fromConfig(env.config, {\r\n        parser: customBitbucketRepositoryParser,\r\n        logger: env.logger,\r\n      }),\r\n      LdapOrgReaderProcessor.fromConfig(env.config, {\r\n        logger: env.logger,\r\n        groupTransformer: customGroupTransformer,\r\n        userTransformer: customUserTransformer,\r\n      }),\r\n      new UrlReaderProcessor({ reader: env.reader, logger: env.logger }),\r\n      new LocationEntityProcessor({ integrations }),\r\n      new AnnotateLocationEntityProcessor({ integrations }),\r\n      new ScaffolderEntitiesProcessor(),\r\n    ]);\r\n\r\n    const { processingEngine, router } = await builder.setRefreshIntervalSeconds(600).build();\r\n    await processingEngine.start();\r\n    return router;\r\n  }\r\n```\r\nI am getting the following error: `scaffolder error Failed to parse template string: /catalog-info.yaml with error Unexpected token / in JSON at position 0 type=plugin`\r\n\r\nI do not get this error when using `addProcessor`\r\n\r\nThe reason i am not using addProcessor is because i am not able to get the BitbucketDiscoveryProcessor to run given its only added unless the user replaced them all\r\n\r\nhttps://github.com/backstage/backstage/blob/931ca6686789290751d5a1c58d5a0012f2bba60c/plugins/catalog-backend/src/service/NextCatalogBuilder.ts#L407-L419\r\n\r\n\r\n## Possible Solution\r\n\r\n\r\n## Steps to Reproduce\r\n\r\n## Context\r\n\r\n\r\n## Your Environment\r\n\r\n<!--- Include as many relevant details about the environment you experienced the bug in -->\r\n\r\n<!-- ProTip: You can use `yarn backstage-cli info` command in your Backstage App for this section. -->\r\n\r\n- NodeJS Version (v14): Node14\r\n- Operating System and Version (e.g. Ubuntu 14.04): Window10\r\n- Browser Information: Chrome\r\n",
    reactions: {
      url: 'https://api.github.com/repos/backstage/backstage/issues/7661/reactions',
      total_count: 0,
      '+1': 0,
      '-1': 0,
      laugh: 0,
      hooray: 0,
      confused: 0,
      heart: 0,
      rocket: 0,
      eyes: 0,
    },
    timeline_url:
      'https://api.github.com/repos/backstage/backstage/issues/7661/timeline',
    performed_via_github_app: null,
  },
];
