export default {
  type: 'category',
  label: 'Framework',
  link: { type: 'generated-index', title: 'Framework', slug: '/framework' },
  items: [
    {
      type: 'category',
      label: 'Backend System',
      link: {
        type: 'generated-index',
        title: 'Backend System',
        slug: '/backend-system',
      },
      items: [
        'backend-system/index',
        {
          type: 'category',
          label: 'Architecture',
          link: {
            type: 'generated-index',
            title: 'Architecture',
            slug: '/architecture',
          },
          items: [
            'backend-system/architecture/index',
            'backend-system/architecture/services',
            'backend-system/architecture/plugins',
            'backend-system/architecture/extension-points',
            'backend-system/architecture/modules',
            'backend-system/architecture/feature-loaders',
            'backend-system/architecture/naming-patterns',
          ],
        },
        {
          type: 'category',
          label: 'Building Backends',
          link: {
            type: 'generated-index',
            title: 'Building Backends',
            slug: '/building-backends',
          },
          items: [
            'backend-system/building-backends/index',
            'backend-system/building-backends/migrating',
          ],
        },
        {
          type: 'category',
          label: 'Building Plugins & Modules',
          link: {
            type: 'generated-index',
            title: 'Building Plugins & Modules',
            slug: '/building-plugins-and-modules',
          },
          items: [
            'backend-system/building-plugins-and-modules/index',
            'backend-system/building-plugins-and-modules/testing',
            'backend-system/building-plugins-and-modules/migrating',
          ],
        },
        {
          type: 'category',
          label: 'Core Services',
          link: {
            type: 'generated-index',
            title: 'Core Services',
            slug: '/core-services',
          },
          items: [
            'backend-system/core-services/index',
            'backend-system/core-services/auditor',
            'backend-system/core-services/auth',
            'backend-system/core-services/cache',
            'backend-system/core-services/database',
            'backend-system/core-services/discovery',
            'backend-system/core-services/http-auth',
            'backend-system/core-services/http-router',
            'backend-system/core-services/identity',
            'backend-system/core-services/lifecycle',
            'backend-system/core-services/logger',
            'backend-system/core-services/permissions',
            'backend-system/core-services/permissions-registry',
            'backend-system/core-services/plugin-metadata',
            'backend-system/core-services/root-config',
            'backend-system/core-services/root-health',
            'backend-system/core-services/root-http-router',
            'backend-system/core-services/root-lifecycle',
            'backend-system/core-services/root-logger',
            'backend-system/core-services/scheduler',
            'backend-system/core-services/token-manager',
            'backend-system/core-services/url-reader',
            'backend-system/core-services/user-info',
            'backend-system/core-services/actions-registry',
            'backend-system/core-services/actions',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'New Frontend System',
      link: {
        type: 'generated-index',
        title: 'New Frontend System',
        slug: '/new-frontend-system',
      },
      items: [
        'frontend-system/index',
        {
          type: 'category',
          label: 'Architecture',
          link: {
            type: 'generated-index',
            title: 'Architecture',
            slug: '/architecture',
          },
          items: [
            'frontend-system/architecture/index',
            'frontend-system/architecture/app',
            'frontend-system/architecture/plugins',
            'frontend-system/architecture/extensions',
            'frontend-system/architecture/extension-blueprints',
            'frontend-system/architecture/extension-overrides',
            'frontend-system/architecture/references',
            'frontend-system/architecture/utility-apis',
            'frontend-system/architecture/routes',
            'frontend-system/architecture/naming-patterns',
            'frontend-system/architecture/migrations',
          ],
        },
        {
          type: 'category',
          label: 'Building Plugins',
          link: {
            type: 'generated-index',
            title: 'Building Plugins',
            slug: '/building-plugins',
          },
          items: [
            'frontend-system/building-plugins/index',
            'frontend-system/building-plugins/testing',
            'frontend-system/building-plugins/common-extension-blueprints',
            'frontend-system/building-plugins/built-in-data-refs',
            'frontend-system/building-plugins/migrating',
          ],
        },
        {
          type: 'category',
          label: 'Building Apps',
          link: {
            type: 'generated-index',
            title: 'Building Apps',
            slug: '/building-apps',
          },
          items: [
            'frontend-system/building-apps/index',
            'frontend-system/building-apps/configuring-extensions',
            'frontend-system/building-apps/built-in-extensions',
            'frontend-system/building-apps/plugin-conversion',
            'frontend-system/building-apps/migrating',
          ],
        },
        {
          type: 'category',
          label: 'Utility APIs',
          link: {
            type: 'generated-index',
            title: 'Utility APIs',
            slug: '/utility-apis',
          },
          items: [
            'frontend-system/utility-apis/index',
            'frontend-system/utility-apis/creating',
            'frontend-system/utility-apis/consuming',
            'frontend-system/utility-apis/configuring',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tooling',
      link: { type: 'generated-index', title: 'Tooling', slug: '/tooling' },
      items: [
        'tooling/cli/overview',
        'tooling/cli/build-system',
        'tooling/cli/commands',
        'tooling/cli/templates',
        {
          type: 'category',
          label: 'Local Development',
          items: [
            'tooling/local-dev/linking-local-packages',
            'tooling/local-dev/debugging',
            'tooling/local-dev/profiling',
          ],
        },
        'tooling/package-metadata',
      ],
    },
    {
      type: 'category',
      label: 'User Interface',
      link: {
        type: 'generated-index',
        title: 'User Interface',
        slug: '/user-interface',
      },
      items: [
        'conf/user-interface/index',
        'conf/user-interface/logo',
        'conf/user-interface/icons',
        'conf/user-interface/sidebar',
      ],
    },
  ],
};
