# Documentation: https://backstage.io/docs/getting-started/ci
# Other CI systems: https://backstage.io/docs/getting-started/ci#other-ci-systems
name: PR CI build

on:
  pull_request: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      # Beginning of yarn setup
      - name: use node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
      - name: install and enable corepack
        run: |
          npm install -g corepack
          corepack enable
      - name: cache all node_modules
        id: cache-modules
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock', '**/package.json') }}
      - name: find location of global yarn cache
        id: yarn-cache
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: cache global yarn cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        if: steps.cache-modules.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: yarn install
        run: yarn install --immutable
      # End of yarn setup

      - name: lint
        run: yarn backstage-cli repo lint

      - name: type checking and declarations
        run: yarn tsc:full

      - name: deprecations
        run: yarn backstage-cli repo list-deprecations

      - name: tests
        run: yarn backstage-cli repo test

      - name: build
        run: yarn build:all

      - name: config check
        run: yarn backstage-cli config:check --lax --strict --config app-config.yaml --config app-config.production.yaml

      # Optional: Docker builds can be slow. Consider moving this to a merge
      # or scheduled workflow if it slows down your pull request feedback loop.
      - name: docker build
        env:
          DOCKER_BUILDKIT: 1
        run: yarn build-image
