/*
 * Copyright 2020 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import sanitizeHtml from 'sanitize-html';

// whitelist inspired by: https://github.com/github/html-pipeline/blob/master/lib/html/pipeline/sanitization_filter.rb#L44
export const sanitizeOptions: sanitizeHtml.IOptions = {
  allowedTags: [
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'h7',
    'h8',
    'br',
    'b',
    'i',
    'strong',
    'em',
    'a',
    'pre',
    'code',
    'img',
    'tt',
    'div',
    'ins',
    'del',
    'sup',
    'sub',
    'p',
    'ol',
    'ul',
    'table',
    'thead',
    'tbody',
    'tfoot',
    'blockquote',
    'dl',
    'dt',
    'dd',
    'kbd',
    'q',
    'samp',
    'var',
    'hr',
    'ruby',
    'rt',
    'rp',
    'li',
    'tr',
    'td',
    'th',
    's',
    'strike',
    'summary',
    'details',
  ],
  allowedAttributes: {
    a: ['href'],
    img: ['src', 'longdesc'],
    div: ['itemscope', 'itemtype'],
    blockquote: ['cite'],
    del: ['cite'],
    ins: ['cite'],
    q: ['cite'],
    '*': [
      'abbr',
      'accept',
      'accept-charset',
      'accesskey',
      'action',
      'align',
      'alt',
      'axis',
      'border',
      'cellpadding',
      'cellspacing',
      'char',
      'charoff',
      'charset',
      'checked',
      'clear',
      'cols',
      'colspan',
      'color',
      'compact',
      'coords',
      'datetime',
      'dir',
      'disabled',
      'enctype',
      'for',
      'frame',
      'headers',
      'height',
      'hreflang',
      'hspace',
      'ismap',
      'label',
      'lang',
      'maxlength',
      'media',
      'method',
      'multiple',
      'name',
      'nohref',
      'noshade',
      'nowrap',
      'open',
      'prompt',
      'readonly',
      'rel',
      'rev',
      'rows',
      'rowspan',
      'rules',
      'scope',
      'selected',
      'shape',
      'size',
      'span',
      'start',
      'summary',
      'tabindex',
      'target',
      'title',
      'type',
      'usemap',
      'valign',
      'value',
      'vspace',
      'width',
      'itemprop',
    ],
  },
};

export const sanitzeContent = (content: string, options = sanitizeOptions) => {
  return sanitizeHtml(content, options);
};
