/*
 * Copyright 2022 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import {
  canExpand,
  FormContextType,
  getTemplate,
  getUiOptions,
  ObjectFieldTemplateProps,
  RJSFSchema,
  StrictRJSFSchema,
} from '@rjsf/utils';
import { Box } from '@backstage/ui';

export default function ObjectFieldTemplate<
  T = any,
  S extends StrictRJSFSchema = RJSFSchema,
  F extends FormContextType = any,
>({
  description,
  title,
  properties,
  required,
  disabled,
  readonly,
  uiSchema,
  idSchema,
  schema,
  formData,
  onAddClick,
  registry,
}: ObjectFieldTemplateProps<T, S, F>) {
  const uiOptions = getUiOptions<T, S, F>(uiSchema);
  const TitleFieldTemplate = getTemplate<'TitleFieldTemplate', T, S, F>(
    'TitleFieldTemplate',
    registry,
    uiOptions,
  );
  const DescriptionFieldTemplate = getTemplate<
    'DescriptionFieldTemplate',
    T,
    S,
    F
  >('DescriptionFieldTemplate', registry, uiOptions);
  const {
    ButtonTemplates: { AddButton },
  } = registry.templates;

  const isNested =
    idSchema.$id !== 'root' &&
    (idSchema.$id.includes('.') || idSchema.$id.includes('_'));

  const isRoot = idSchema.$id === 'root';
  const hasTitle = !isRoot && (uiOptions.title || title);
  const hasDescription = !isRoot && (uiOptions.description || description);

  const isAutoGeneratedTitle = title && /^.+-\d+$/.test(title);

  if (isNested || isAutoGeneratedTitle) {
    return (
      <Box>
        {properties.map(element => element.content)}
        {canExpand<T, S, F>(schema, uiSchema, formData) && (
          <Box mt="3">
            <AddButton
              onClick={onAddClick(schema)}
              disabled={disabled || readonly}
              className="object-property-expand"
              uiSchema={uiSchema}
              registry={registry}
            />
          </Box>
        )}
      </Box>
    );
  }

  return (
    <Box>
      {hasTitle && (
        <TitleFieldTemplate
          id={`${idSchema.$id}__title`}
          title={(title || uiOptions.title) as string}
          required={required}
          schema={schema}
          uiSchema={uiSchema}
          registry={registry}
        />
      )}
      {hasDescription && (
        <DescriptionFieldTemplate
          id={`${idSchema.$id}__description`}
          description={uiOptions.description || description!}
          schema={schema}
          uiSchema={uiSchema}
          registry={registry}
        />
      )}
      {properties.map(element => element.content)}
      {canExpand<T, S, F>(schema, uiSchema, formData) && (
        <Box mt="3">
          <AddButton
            onClick={onAddClick(schema)}
            disabled={disabled || readonly}
            className="object-property-expand"
            uiSchema={uiSchema}
            registry={registry}
          />
        </Box>
      )}
    </Box>
  );
}
