compressionLevel: mixed

enableGlobalCache: true

httpTimeout: 300000

npmRegistryServer: 'https://registry.npmjs.org/'

nodeLinker: node-modules

plugins:
  - checksum: a6895be0b30a75db6fddafedff143f82ccbd74656bad97775c6a0b9eba6e6ea6b7d66a8e9d0c8505755a981e86b7c6c1c9334ead299a857cf8d6e243957b0bab
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/tags/main/yarn-plugin"

yarnPath: ../../.yarn/releases/yarn-4.8.1.cjs
