compressionLevel: mixed

enableGlobalCache: true

httpTimeout: 300000

npmRegistryServer: 'https://registry.npmjs.org/'

nodeLinker: node-modules

plugins:
  - checksum: e036bbabee4fda5a34aed96597e1fa22a0fc753bc7737c525c1b7e37d626f4894e71a01fe7440458a3d034b7f9e648c394cebfb3b47a75b731b16e5b8d50fe60
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/tags/main/yarn-plugin"

yarnPath: ../../.yarn/releases/yarn-4.8.1.cjs
