import type { ChangelogProps } from '../types';

export const changelog_0_1_0: ChangelogProps[] = [
  {
    components: [],
    version: '0.1.0',
    description: `**BREAKING**: Merged the Stack and Inline component into a single component called Flex.`,
    prs: ['28634'],
    type: 'breaking',
    commitSha: '72c9800',
  },
  {
    components: [],
    version: '0.1.0',
    description: `This is the first alpha release for Canon. As part of this release we are introducing 5 layout components and 7 components. All theming is done through CSS variables.`,
    prs: ['28562'],
    type: 'breaking',
    commitSha: '65f4acc',
  },
  {
    components: [],
    version: '0.1.0',
    description: `**BREAKING**: Fixing css structure and making sure that props are applying the correct styles for all responsive values.`,
    prs: ['28630'],
    type: 'breaking',
    commitSha: '1e4ccce',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Updated core CSS tokens and fixing the Button component accordingly.`,
    prs: ['28789'],
    type: 'breaking',
    commitSha: '8309bdb',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Removed client directive as they are not needed in React 18.`,
    prs: ['28626'],
    type: 'fix',
    commitSha: '989af25',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Fix spacing props not being applied for custom values.`,
    prs: ['28770'],
    type: 'fix',
    commitSha: 'f44e5cf',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Removed older versions of React packages as a preparatory step for upgrading to React 19. This commit does not introduce any functional changes, but removes dependencies on previous React versions, allowing for a cleaner upgrade path in subsequent commits.`,
    prs: ['28579'],
    type: 'fix',
    commitSha: '58ec9e7',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Updated core CSS tokens and fixing the Button component accordingly.`,
    prs: ['28789'],
    type: 'breaking',
    commitSha: '8309bdb',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Fix spacing props not being applied for custom values.`,
    prs: ['28770'],
    type: 'fix',
    commitSha: 'f44e5cf',
  },
  {
    components: [],
    version: '0.1.0',
    description: `**BREAKING**: Merged the Stack and Inline component into a single component called Flex.`,
    prs: ['28634'],
    type: 'breaking',
    commitSha: '72c9800',
  },
  {
    components: [],
    version: '0.1.0',
    description: `**BREAKING**: Fixing css structure and making sure that props are applying the correct styles for all responsive values.`,
    prs: ['28630'],
    type: 'breaking',
    commitSha: '1e4ccce',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Removed client directive as they are not needed in React 18.`,
    prs: ['28626'],
    type: 'fix',
    commitSha: '989af25',
  },
  {
    components: [],
    version: '0.1.0',
    description: `Removed older versions of React packages as a preparatory step for upgrading to React 19. This commit does not introduce any functional changes, but removes dependencies on previous React versions, allowing for a cleaner upgrade path in subsequent commits.`,
    prs: ['28579'],
    type: 'fix',
    commitSha: '58ec9e7',
  },
  {
    components: [],
    version: '0.1.0',
    description: `This is the first alpha release for Canon. As part of this release we are introducing 5 layout components and 7 components. All theming is done through CSS variables.`,
    prs: ['28562'],
    type: 'breaking',
    commitSha: '65f4acc',
  },
];
