import type { ChangelogProps } from '../types';

export const changelog_0_3_0: ChangelogProps[] = [
  {
    components: ['datatable'],
    version: '0.3.0',
    description: 'Add `DataTable` component',
    prs: ['29484', '29603'],
    type: 'new',
  },
  {
    components: ['select'],
    version: '0.3.0',
    description: 'Add `Select` component',
    prs: ['29440'],
    type: 'new',
  },
  {
    components: ['avatar'],
    version: '0.3.0',
    description: 'Add `Avatar` component',
    prs: ['29594'],
    type: 'new',
  },
  {
    components: ['collapsible'],
    version: '0.3.0',
    description: 'Add `Collapsible` component',
    prs: ['29617'],
    type: 'new',
  },
  {
    components: ['textfield'],
    version: '0.3.0',
    description: 'Add `TextField` component instead of `Field` + `Input`',
    prs: ['29364'],
    type: 'new',
  },
  {
    components: ['datatable'],
    version: '0.3.0',
    description: 'Add `TableCellProfile`',
    prs: ['29600'],
    type: 'new',
  },
  {
    components: [],
    version: '0.3.0',
    description: 'Add breakpoint hooks - `up()` and `down()`',
    prs: ['29564'],
    type: 'new',
  },
  {
    components: [],
    version: '0.3.0',
    description: 'Add gray scale css tokens',
    prs: ['29543'],
    type: 'new',
  },
  {
    components: [],
    version: '0.3.0',
    description:
      'Update CSS styling API using `[data-___]` instead of class names for props',
    prs: ['29560'],
  },
  {
    components: ['checkbox'],
    version: '0.3.0',
    description: 'Update `Checkbox` dark mode',
    prs: ['29544'],
  },
  {
    components: ['container'],
    version: '0.3.0',
    description: 'Update `Container` styles',
    prs: ['29475'],
  },
  {
    components: ['menu'],
    version: '0.3.0',
    description: 'Update `Menu` styles',
    prs: ['29351'],
  },
  {
    components: ['select'],
    version: '0.3.0',
    description: 'Fix `Select` styles on small sizes + with long option names',
    prs: ['29545'],
  },
  {
    components: ['link'],
    version: '0.3.0',
    description: 'Fix render prop on `Link`',
    prs: ['29247'],
  },
  {
    components: ['textfield', 'select'],
    version: '0.3.0',
    description: 'Remove `Field` from `TextField` + `Select`',
    prs: ['29482'],
  },
  {
    components: ['text', 'heading'],
    version: '0.3.0',
    description: 'Update `textDecoration` to `none` on `Text` / `Heading`',
    prs: ['29357'],
  },
  {
    components: ['text', 'heading'],
    version: '0.3.0',
    description: 'Update `textDecoration` to `none` on `Text` / `Heading`',
    prs: ['29357'],
  },
  {
    components: [],
    version: '0.3.0',
    description: 'Docs - Use stories from Storybook for all examples in Nextjs',
    prs: ['29306'],
  },
  {
    components: [],
    version: '0.3.0',
    description: 'Docs - Add release page (this one 🤗)',
    prs: ['29461'],
  },
  {
    components: [],
    version: '0.3.0',
    description: 'Docs - Add docs for Menu, Link',
    prs: ['29576'],
  },
  {
    components: [],
    version: '0.3.0',
    description: 'Fix CSS watch mode',
    prs: ['29352'],
  },
];
