import type { ChangelogProps } from '../types';

export const changelog_0_7_2: ChangelogProps[] = [
  {
    components: ['tabs', 'header'],
    version: '0.7.2',
    description: `Making href mandatory in tabs that are part of a Header component`,
    prs: ['31343'],
    type: 'fix',
    commitSha: '3c921c5',
  },
  {
    components: ['button-link'],
    version: '0.7.2',
    description: `Add react router for internal routing for ButtonLinks`,
    prs: ['31276'],
    type: 'new',
    commitSha: '5c21e45',
  },
  {
    components: ['tabs'],
    version: '0.7.2',
    description: `Remove auto selection of tabs for tabs that all have href defined`,
    prs: ['31281'],
    type: 'fix',
    commitSha: '9781815',
  },
  {
    components: ['menu'],
    version: '0.7.2',
    description: `Using react router for internal links in the Menu component`,
    prs: ['31339'],
    type: 'fix',
    commitSha: 'f6dff5b',
  },
  {
    components: ['button', 'tooltip'],
    version: '0.7.2',
    description: `Enable tooltips on disabled buttons with automatic wrapper`,
    prs: ['31230'],
    type: 'fix',
    commitSha: 'a9b88be',
  },
  {
    components: [],
    version: '0.7.2',
    description: `Avoid overriding onChange when spreading props`,
    prs: ['31232'],
    type: 'fix',
    commitSha: '4adbb03',
  },
  {
    components: ['tabs'],
    version: '0.7.2',
    description: `remove default selection of tab`,
    prs: ['31216'],
    type: 'fix',
    commitSha: '827340f',
  },
  {
    components: ['searchfield', 'header'],
    version: '0.7.2',
    description: `Improved SearchField component flex layout and animations. Fixed SearchField behavior in Header components by switching from width-based transitions to flex-basis transitions for better responsive behavior. Added new Storybook stories to test SearchField integration with Header component.`,
    prs: ['31158'],
    type: 'fix',
    commitSha: '9a47125',
  },
];
