import type { ChangelogProps } from '../types';

export const changelog_0_7_0: ChangelogProps[] = [
  {
    components: ['datatable', 'table'],
    version: '0.7.0',
    description: `We are moving our DataTable component to React Aria. We removed our DataTable to only use Table as a single and opinionated option for tables. This new structure is made possible by using React Aria under the hood.`,
    prs: ['30654'],
    type: 'breaking',
    commitSha: '0615e54',
  },
  {
    components: ['header-page'],
    version: '0.7.0',
    description: `Backstage UI - HeaderPage - We are updating the breadcrumb to be more visible and accessible.`,
    prs: ['30874'],
    type: 'breaking',
    commitSha: 'b245c9d',
  },
  {
    components: ['menu'],
    version: '0.7.0',
    description: `**Breaking change** We are updating the Menu component to use React Aria under the hood. The structure and all props are changing to follow React Aria's guidance.`,
    prs: ['30908'],
    type: 'breaking',
    commitSha: '800f593',
  },
  {
    components: ['text', 'heading', 'link'],
    version: '0.7.0',
    description: `**Breaking** We are upgrading our \`Text\` component to support all font sizes making the \`Heading\` component redundant. The new \`Text\` component introduces 4 sizes for title and 4 sizes for body text. All of these work in multiple colors and font weights. We improved the \`as\` prop to include all possible values. The \`Link\` component has also been updated to match the new \`Text\` component.`,
    prs: ['30592'],
    type: 'breaking',
    commitSha: 'b0e47f3',
  },
  {
    components: ['select'],
    version: '0.7.0',
    description: `Fixes some styles on the Select component in BUI.`,
    prs: ['30642'],
    type: 'fix',
    commitSha: 'de89a3d',
  },
  {
    components: ['card'],
    version: '0.7.0',
    description: `Export CardHeader, CardBody and CardFooter from Card component index`,
    prs: ['30882'],
    type: 'fix',
    commitSha: 'a251b3e',
  },
  {
    components: ['tag-group'],
    version: '0.7.0',
    description: `Add new TagGroup component to Backstage UI.`,
    prs: ['30919'],
    type: 'new',
    commitSha: 'f761306',
  },
  {
    components: ['header', 'header-page'],
    version: '0.7.0',
    description: `Fixes a couple of small bugs in BUI including setting H1 and H2 correctly on the Header and HeaderPage.`,
    prs: ['30636'],
    type: 'fix',
    commitSha: '75fead9',
  },
  {
    components: ['tooltip'],
    version: '0.7.0',
    description: `Update styling of Tooltip element`,
    prs: ['30591'],
    type: 'fix',
    commitSha: 'e7ff178',
  },
  {
    components: ['header-page', 'header'],
    version: '0.7.0',
    description: `**Breaking change** Move breadcrumb to fit in the \`HeaderPage\` instead of the \`Header\` in Backstage UI.`,
    prs: ['30701'],
    type: 'fix',
    commitSha: '230b410',
  },
  {
    components: [],
    version: '0.7.0',
    description: `We are motion away from \`motion\` to use \`gsap\` instead to make Backstage UI backward compatible with React 17.`,
    prs: ['30626'],
    type: 'fix',
    commitSha: '2f9a084',
  },
  {
    components: ['menu'],
    version: '0.7.0',
    description: `Updated Menu component in Backstage UI to use useId() from React Aria instead of React to support React 17.`,
    prs: ['30675'],
    type: 'fix',
    commitSha: 'd4e603e',
  },
  {
    components: ['select'],
    version: '0.7.0',
    description: `Remove stylesheet import from Select component.`,
    prs: ['30800'],
    type: 'fix',
    commitSha: '8bdc491',
  },
  {
    components: ['searchfield'],
    version: '0.7.0',
    description: `Add \`startCollapsed\` prop on the \`SearchField\` component in BUI.`,
    prs: ['30729'],
    type: 'new',
    commitSha: '404b426',
  },
  {
    components: ['header'],
    version: '0.7.0',
    description: `Adds onTabSelectionChange to ui header component.`,
    prs: ['30588'],
    type: 'fix',
    commitSha: 'e0e886f',
  },
  {
    components: ['datatable', 'table'],
    version: '0.7.0',
    description: `We are moving our DataTable component to React Aria. We removed our DataTable to only use Table as a single and opinionated option for tables. This new structure is made possible by using React Aria under the hood.`,
    prs: ['30654'],
    type: 'breaking',
    commitSha: '0615e54',
  },
  {
    components: ['header-page', 'header'],
    version: '0.7.0',
    description: `**Breaking change** Move breadcrumb to fit in the \`HeaderPage\` instead of the \`Header\` in Backstage UI.`,
    prs: ['30701'],
    type: 'fix',
    commitSha: '230b410',
  },
  {
    components: ['select'],
    version: '0.7.0',
    description: `Remove stylesheet import from Select component.`,
    prs: ['30800'],
    type: 'fix',
    commitSha: '8bdc491',
  },
  {
    components: ['searchfield'],
    version: '0.7.0',
    description: `Add \`startCollapsed\` prop on the \`SearchField\` component in BUI.`,
    prs: ['30729'],
    type: 'new',
    commitSha: '404b426',
  },
  {
    components: ['menu'],
    version: '0.7.0',
    description: `Updated Menu component in Backstage UI to use useId() from React Aria instead of React to support React 17.`,
    prs: ['30675'],
    type: 'fix',
    commitSha: 'd4e603e',
  },
  {
    components: ['select'],
    version: '0.7.0',
    description: `Fixes some styles on the Select component in BUI.`,
    prs: ['30642'],
    type: 'fix',
    commitSha: 'de89a3d',
  },
  {
    components: ['header', 'header-page'],
    version: '0.7.0',
    description: `Fixes a couple of small bugs in BUI including setting H1 and H2 correctly on the Header and HeaderPage.`,
    prs: ['30636'],
    type: 'fix',
    commitSha: '75fead9',
  },
  {
    components: [],
    version: '0.7.0',
    description: `We are motion away from \`motion\` to use \`gsap\` instead to make Backstage UI backward compatible with React 17.`,
    prs: ['30626'],
    type: 'fix',
    commitSha: '2f9a084',
  },
  {
    components: ['text', 'heading', 'link'],
    version: '0.7.0',
    description: `**Breaking** We are upgrading our \`Text\` component to support all font sizes making the \`Heading\` component redundant. The new \`Text\` component introduces 4 sizes for title and 4 sizes for body text. All of these work in multiple colors and font weights. We improved the \`as\` prop to include all possible values. The \`Link\` component has also been updated to match the new \`Text\` component.`,
    prs: ['30592'],
    type: 'breaking',
    commitSha: 'b0e47f3',
  },
  {
    components: ['tooltip'],
    version: '0.7.0',
    description: `Update styling of Tooltip element`,
    prs: ['30591'],
    type: 'fix',
    commitSha: 'e7ff178',
  },
  {
    components: ['header'],
    version: '0.7.0',
    description: `Adds onTabSelectionChange to ui header component.`,
    prs: ['30588'],
    type: 'fix',
    commitSha: 'e0e886f',
  },
];
