import type { ChangelogProps } from '../types';

export const changelog_0_8_0: ChangelogProps[] = [
  {
    components: ['password-field', 'textfield'],
    version: '0.8.0',
    description: `**BREAKING**: Added a new \`PasswordField\` component. As part of this change, the \`password\` and \`search\` types have been removed from \`TextField\`.`,
    prs: ['31238'],
    type: 'breaking',
    commitSha: '9acc1d6',
  },
  {
    components: [],
    version: '0.8.0',
    description: `**BREAKING** Restructure Backstage UI component styling to use CSS Modules instead of pure CSS. We don't expect this to be an issue in practice but it is important to call out that all styles are now loaded through CSS modules with generated class names. We are still providing fixed class names for all components to allow anyone to style their Backstage instance.`,
    prs: ['31399'],
    type: 'breaking',
    commitSha: 'b0d11b5',
  },
  {
    components: ['scrollarea'],
    version: '0.8.0',
    description: `**BREAKING** The ScrollArea component has been removed from Backstage UI because it did not meet our accessibility standards.`,
    prs: ['31409'],
    type: 'breaking',
    commitSha: '0c53517',
  },
  {
    components: ['icon'],
    version: '0.8.0',
    description: `**BREAKING** Remove Icon component in Backstage UI. This component was creating issue for tree-shaking. It is recommended to use icons from @remixicon/react until we found a better alternative in Backstage UI.`,
    prs: ['31407'],
    type: 'breaking',
    commitSha: '7b319c5',
  },
  {
    components: ['dialog'],
    version: '0.8.0',
    description: `Adding a new Dialog component to Backstage UI.`,
    prs: ['31371'],
    type: 'fix',
    commitSha: '2591b42',
  },
  {
    components: ['tabs'],
    version: '0.8.0',
    description: `remove default selection of tab`,
    prs: ['31216'],
    type: 'fix',
    commitSha: '827340f',
  },
  {
    components: [],
    version: '0.8.0',
    description: `Fix margin utility classes in Backstage UI.`,
    prs: ['31389'],
    type: 'fix',
    commitSha: '5dc17cc',
  },
  {
    components: ['menu'],
    version: '0.8.0',
    description: `Fix scroll jumping when opening menu in Backstage UI.`,
    prs: ['31394'],
    type: 'fix',
    commitSha: '85faee0',
  },
  {
    components: ['tabs', 'header'],
    version: '0.8.0',
    description: `Making href mandatory in tabs that are part of a Header component`,
    prs: ['31343'],
    type: 'fix',
    commitSha: '3c921c5',
  },
  {
    components: [],
    version: '0.8.0',
    description: `Update react-aria-components to version 1.13.0`,
    prs: ['31367'],
    type: 'fix',
    commitSha: 'df7d2cf',
  },
  {
    components: ['table'],
    version: '0.8.0',
    description: `Fix table sorting icon position in Backstage UI.`,
    prs: ['31393'],
    type: 'fix',
    commitSha: '507ee55',
  },
  {
    components: ['menu'],
    version: '0.8.0',
    description: `Add new \`virtualized\`, \`maxWidth\` and \`maxHeight\` props to \`Menu\`, \`MenuListBox\`, \`MenuAutocomplete\` and \`MenuAutocompleteListBox\` to allow for virtalization of long lists inside menus.`,
    prs: ['31375'],
    type: 'new',
    commitSha: '8b7c3c9',
  },
  {
    components: ['box', 'container', 'flex', 'grid'],
    version: '0.8.0',
    description: `Added support for data attributes in \`<Box />\`, \`<Container />\`, \`<Flex />\`, and \`<Grid />\` components, ensuring they are correctly applied to the rendered elements.`,
    prs: ['31374'],
    type: 'new',
    commitSha: 'b940062',
  },
  {
    components: ['scrollarea', 'card'],
    version: '0.8.0',
    description: `Cleaning up Backstage UI props definitions as well as removing ScrollArea in Card to improve accessibility.`,
    prs: ['31404'],
    type: 'fix',
    commitSha: '206c801',
  },
  {
    components: ['button-link'],
    version: '0.8.0',
    description: `Add react router for internal routing for ButtonLinks`,
    prs: ['31276'],
    type: 'new',
    commitSha: '5c21e45',
  },
  {
    components: [],
    version: '0.8.0',
    description: `Added a background color default on the body`,
    prs: ['31365'],
    type: 'new',
    commitSha: '865bce8',
  },
  {
    components: [],
    version: '0.8.0',
    description: `We are restructuring our CSS to have a better layer structure.`,
    prs: ['31362'],
    type: 'fix',
    commitSha: 'af4d9b4',
  },
  {
    components: ['searchfield', 'header'],
    version: '0.8.0',
    description: `Improved SearchField component flex layout and animations. Fixed SearchField behavior in Header components by switching from width-based transitions to flex-basis transitions for better responsive behavior. Added new Storybook stories to test SearchField integration with Header component.`,
    prs: ['31158'],
    type: 'fix',
    commitSha: '9a47125',
  },
  {
    components: ['tabs'],
    version: '0.8.0',
    description: `Remove auto selection of tabs for tabs that all have href defined`,
    prs: ['31281'],
    type: 'fix',
    commitSha: '9781815',
  },
  {
    components: [],
    version: '0.8.0',
    description: `Avoid overriding onChange when spreading props`,
    prs: ['31232'],
    type: 'fix',
    commitSha: '4adbb03',
  },
  {
    components: ['menu'],
    version: '0.8.0',
    description: `Using react router for internal links in the Menu component`,
    prs: ['31339'],
    type: 'fix',
    commitSha: 'f6dff5b',
  },
];
