const INITIALIZE = 'FILTERS_INITIALIZE';
const UPDATE_LAYOUT = 'FILTERS_UPDATE_LAYOUT';
const UPDATE_VALUE = 'FILTERS_UPDATE_VALUE';
const REPLACE_VALUE = 'FILTERS_REPLACE_VALUE';
const RESET = 'FILTERS_RESET';

export { INITIALIZE, UPDATE_LAYOUT, UPDATE_VALUE, REPLACE_VALUE, RESET };
