apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-cli-module-test-jest
  title: '@backstage/cli-module-test-jest'
  description: CLI module for Backstage CLI
spec:
  lifecycle: experimental
  type: backstage-cli-module
  owner: tooling-maintainers
