/*
 * Copyright 2025 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import { ActionsRegistryService } from '@backstage/backend-plugin-api/alpha';
import { CatalogService } from '@backstage/plugin-catalog-node';
import { InputError, ForwardedError } from '@backstage/errors';

export const createRegisterCatalogEntitiesAction = ({
  catalog,
  actionsRegistry,
}: {
  catalog: CatalogService;
  actionsRegistry: ActionsRegistryService;
}) => {
  actionsRegistry.register({
    name: 'register-catalog-entities',
    title: 'Register Catalog Entities',
    attributes: {
      destructive: false,
      readOnly: false,
      idempotent: true,
    },
    description: `Register entities defined remotely (create new Locations).

This tool is analogous to the "register existing components" function you see in the Backstage dashboard,
where you supply a URL link that allows for the downloading of a 'catalog-info.yaml' file that 
defines the various Entities (Components, Systems, Resources, APIs, Users, and Groups) you want to 
create or import into the Backstage catalog.

The action within the catalog results in the creation of a Location entity that is the parent of owner
of all the additional entities defined in the 'catalog-info.yaml' file.

The dynamically generated, random UUID created to go along with the newly created Location entity is returned
to the caller.  That UUID can be later used if you want to unregister or delete the Location entity and all
of its children entities.

/eExample invocation and the output from the invocation:
  # Register a Location from a GitHub URL
  register-catalog-entities locationURL: https://github.com/redhat-ai-dev/model-catalog-example/blob/main/developer-model-service/catalog-info.yaml
  Output: {
    "locationID": "aaaa-bbbb-cccc-dddd"
  }      
`,
    schema: {
      input: z =>
        z.object({
          locationURL: z
            .string()
            .describe(
              `URL reference to the catalog-info.yaml file that describes what entities to import.`,
            ),
        }),
      output: z =>
        z.object({
          locationID: z
            .string()
            .optional()
            .describe('The location ID generated by the registration'),
        }),
    },
    action: async ({ input, credentials }) => {
      if (!input.locationURL || input.locationURL === '') {
        throw new InputError('a location URL must be specified');
      }

      // Validate that the locationURL is a valid URL
      try {
        // eslint-disable-next-line no-new
        new URL(input.locationURL);
      } catch {
        throw new InputError(
          `locationURL "${input.locationURL}" an invalid URL`,
        );
      }
      try {
        const locReq = {
          type: 'url',
          target: input.locationURL,
        };
        const result = await catalog.addLocation(locReq, {
          credentials,
        });

        return {
          output: {
            locationID: result.location.id,
          },
        };
      } catch (error) {
        throw new ForwardedError(
          `catalog import of "${input.locationURL} failed"`,
          error,
        );
      }
    },
  });
};
