scalar JSON
scalar JSONObject

type EntityMetadataAnnotation {
  key: String!
  value: String!
}

type EntityMetadata {
  name: String!
  namespace: String!
  annotations: JSONObject
  annotation(name: String): JSON
  labels: JSONObject
  uid: String!
  etag: String!
  generation: Int!
}

type CatalogEntity {
  apiVersion: String!
  kind: String!
  metadata: EntityMetadata!
}

type CatalogQuery {
  list: [CatalogEntity!]!
}

type Query {
  catalog: CatalogQuery!
}
