/*
 * Copyright 2026 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createMockDirectory } from '@backstage/backend-test-utils';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fixYarnPatches } from './fixYarnPatches';
import { verifyYarnPatches } from './verifyYarnPatches';

const mockDir = createMockDirectory();

const LOCKFILE_HEADER = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0
`;

function repository(options?: { target?: boolean }) {
  const exampleVersion = options?.target ? '1.0.1' : '1.0.0';
  const otherVersion = options?.target ? '2.0.1' : '2.0.0';
  return {
    'package.json': JSON.stringify({
      name: 'root',
      resolutions: {
        '@backstage/example': `patch:@backstage/example@npm%3A${exampleVersion}#~/.yarn/patches/example.patch`,
        '@backstage/other': `patch:@backstage/other@npm%3A${otherVersion}#~/.yarn/patches/other.patch`,
      },
    }),
    'backstage.json': JSON.stringify({ version: '1.0.1' }),
    '.yarn': {
      patches: {
        'example.patch': 'example patch',
        'other.patch': 'other patch',
      },
    },
    'yarn.lock': `${LOCKFILE_HEADER}
"@backstage/example@patch:@backstage/example@npm%3A${exampleVersion}#~/.yarn/patches/example.patch":
  version: ${exampleVersion}
  resolution: "@backstage/example@patch:@backstage/example@npm%3A${exampleVersion}#~/.yarn/patches/example.patch::version=${exampleVersion}&hash=aaaaaa"
  languageName: node
  linkType: hard

"@backstage/other@patch:@backstage/other@npm%3A${otherVersion}#~/.yarn/patches/other.patch":
  version: ${otherVersion}
  resolution: "@backstage/other@patch:@backstage/other@npm%3A${otherVersion}#~/.yarn/patches/other.patch::version=${otherVersion}&hash=bbbbbb"
  languageName: node
  linkType: hard
`,
  };
}

const fetchRelease = async () =>
  new Response(
    JSON.stringify({
      releaseVersion: '1.0.1',
      packages: [
        { name: '@backstage/example', version: '1.0.1' },
        { name: '@backstage/other', version: '2.0.1' },
      ],
    }),
  );

const fetchSingleUpdate = async () =>
  new Response(
    JSON.stringify({
      releaseVersion: '1.0.1',
      packages: [
        { name: '@backstage/example', version: '1.0.1' },
        { name: '@backstage/other', version: '2.0.0' },
      ],
    }),
  );

function singleUpdateRepository() {
  const target = repository({ target: true });
  return {
    ...target,
    'package.json': target['package.json'].replaceAll('2.0.1', '2.0.0'),
    'yarn.lock': target['yarn.lock'].replaceAll('2.0.1', '2.0.0'),
  };
}

function repositoryWithDependencies(options: {
  target: boolean;
  unrelatedVersion: string;
}) {
  const content = repository({ target: options.target });
  const sharedVersion = options.target ? '2.0.0' : '1.0.0';
  return {
    ...content,
    'yarn.lock': `${content['yarn.lock'].replaceAll(
      '  languageName: node\n  linkType: hard',
      `  dependencies:\n    shared: "npm:${sharedVersion}"\n  languageName: node\n  linkType: hard`,
    )}
"shared@npm:${sharedVersion}":
  version: ${sharedVersion}
  resolution: "shared@npm:${sharedVersion}"
  languageName: node
  linkType: hard

"unrelated@npm:^1.0.0":
  version: ${options.unrelatedVersion}
  resolution: "unrelated@npm:${options.unrelatedVersion}"
  languageName: node
  linkType: hard
`,
  };
}

describe('fixYarnPatches', () => {
  beforeEach(() => {
    mockDir.clear();
  });

  it('repairs one forward holdback', async () => {
    mockDir.setContent(repository());
    const install = jest.fn(async rootDir => {
      await fs.writeFile(
        path.join(rootDir, 'yarn.lock'),
        singleUpdateRepository()['yarn.lock'],
      );
    });

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchSingleUpdate,
        install,
      }),
    ).resolves.toMatchObject({ status: 'fixed' });
    expect(install).toHaveBeenCalledTimes(1);
    await expect(
      verifyYarnPatches({ rootDir: mockDir.path, fetch: fetchSingleUpdate }),
    ).resolves.toMatchObject({ errors: [] });
  });

  it('repairs multiple forward holdbacks in one install', async () => {
    mockDir.setContent(repository());
    const originalManifest = await fs.readFile(
      mockDir.resolve('package.json'),
      'utf8',
    );
    const verificationResult = await verifyYarnPatches({
      rootDir: mockDir.path,
      fetch: fetchRelease,
    });
    const install = jest.fn(async rootDir => {
      const manifest = JSON.parse(
        await fs.readFile(path.join(rootDir, 'package.json'), 'utf8'),
      );
      expect(manifest.resolutions).toMatchObject({
        '@backstage/example':
          'patch:@backstage/example@npm%3A1.0.1#~/.yarn/patches/example.patch',
        '@backstage/other':
          'patch:@backstage/other@npm%3A2.0.1#~/.yarn/patches/other.patch',
      });
      await fs.writeFile(
        path.join(rootDir, 'yarn.lock'),
        repository({ target: true })['yarn.lock'],
      );
    });

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install,
        verificationResult,
      }),
    ).resolves.toMatchObject({
      status: 'fixed',
      message: expect.stringContaining(
        "@backstage/example' from '1.0.0' to '1.0.1",
      ),
    });
    expect(install).toHaveBeenCalledTimes(1);
    await expect(
      fs.readFile(mockDir.resolve('package.json'), 'utf8'),
    ).resolves.toBe(
      originalManifest.replace('1.0.0', '1.0.1').replace('2.0.0', '2.0.1'),
    );
    await expect(
      verifyYarnPatches({ rootDir: mockDir.path, fetch: fetchRelease }),
    ).resolves.toMatchObject({ errors: [] });
  });

  it('does not install from a stale verification result', async () => {
    mockDir.setContent(repository());
    const verificationResult = await verifyYarnPatches({
      rootDir: mockDir.path,
      fetch: fetchRelease,
    });
    const manifestPath = mockDir.resolve('package.json');
    const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8'));
    const staleReference = manifest.resolutions['@backstage/example'];
    manifest.resolutions['@backstage/example'] =
      'patch:@backstage/example@npm%3A1.0.1#~/.yarn/patches/example.patch';
    manifest.scripts = { staleReference };
    await fs.writeFile(manifestPath, JSON.stringify(manifest));
    const originalManifest = await fs.readFile(manifestPath, 'utf8');
    const originalLockfile = await fs.readFile(
      mockDir.resolve('yarn.lock'),
      'utf8',
    );
    const install = jest.fn();

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install,
        verificationResult,
      }),
    ).resolves.toMatchObject({ status: 'not-fixable' });
    expect(install).not.toHaveBeenCalled();
    await expect(fs.readFile(manifestPath, 'utf8')).resolves.toBe(
      originalManifest,
    );
    await expect(
      fs.readFile(mockDir.resolve('yarn.lock'), 'utf8'),
    ).resolves.toBe(originalLockfile);
  });

  it.each([
    ['a ranged source', { source: '@backstage/example@npm:^1.0.0' }],
    [
      'an aliased source',
      { source: '@backstage/example@npm:@backstage/other@1.0.0' },
    ],
    ['a non-project-owned patch', { projectOwned: false }],
    [
      'multiple patch paths',
      {
        paths: [
          {
            absolute: '/first.patch',
            relative: '.yarn/patches/first.patch',
          },
          {
            absolute: '/second.patch',
            relative: '.yarn/patches/second.patch',
          },
        ],
      },
    ],
    ['a nested declaration', { location: 'workspace/package.json' }],
  ] as const)('does not repair %s', async (_name, declarationChange) => {
    mockDir.setContent(repository());
    const verificationResult = await verifyYarnPatches({
      rootDir: mockDir.path,
      fetch: fetchRelease,
    });
    Object.assign(
      verificationResult.errors[0].repairHint!.declaration,
      declarationChange,
    );
    const install = jest.fn();

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install,
        verificationResult,
      }),
    ).resolves.toMatchObject({ status: 'not-fixable' });
    expect(install).not.toHaveBeenCalled();
  });

  it('does not repair an ambiguous manifest reference', async () => {
    const content = repository();
    const manifest = JSON.parse(content['package.json']);
    manifest.description = manifest.resolutions['@backstage/example'];
    mockDir.setContent({
      ...content,
      'package.json': JSON.stringify(manifest),
    });
    const install = jest.fn();

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install,
      }),
    ).resolves.toMatchObject({ status: 'not-fixable' });
    expect(install).not.toHaveBeenCalled();
  });

  it('restores project files when Yarn fails', async () => {
    mockDir.setContent(repository());
    const originalManifest = await fs.readFile(
      mockDir.resolve('package.json'),
      'utf8',
    );
    const originalLockfile = await fs.readFile(
      mockDir.resolve('yarn.lock'),
      'utf8',
    );

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install: async () => {
          throw new Error('install failed');
        },
      }),
    ).resolves.toMatchObject({
      status: 'not-fixable',
      message: expect.stringContaining(
        'the original project files were restored',
      ),
    });
    await expect(
      fs.readFile(mockDir.resolve('package.json'), 'utf8'),
    ).resolves.toBe(originalManifest);
    await expect(
      fs.readFile(mockDir.resolve('yarn.lock'), 'utf8'),
    ).resolves.toBe(originalLockfile);
  });

  it('rejects and restores unrelated lockfile changes', async () => {
    mockDir.setContent(repository());
    const originalManifest = await fs.readFile(
      mockDir.resolve('package.json'),
      'utf8',
    );
    const originalLockfile = await fs.readFile(
      mockDir.resolve('yarn.lock'),
      'utf8',
    );
    const unrelatedEntry = `
"unrelated@npm:^1.0.0":
  version: 1.1.0
  resolution: "unrelated@npm:1.1.0"
  languageName: node
  linkType: hard
`;

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install: async rootDir => {
          await fs.writeFile(
            path.join(rootDir, 'yarn.lock'),
            `${repository({ target: true })['yarn.lock']}${unrelatedEntry}`,
          );
        },
      }),
    ).resolves.toMatchObject({
      status: 'not-fixable',
      message: expect.stringContaining('unrelated lockfile changes'),
    });
    await expect(
      fs.readFile(mockDir.resolve('package.json'), 'utf8'),
    ).resolves.toBe(originalManifest);
    await expect(
      fs.readFile(mockDir.resolve('yarn.lock'), 'utf8'),
    ).resolves.toBe(originalLockfile);
  });

  it('rejects an unrelated change alongside overlapping target dependency changes', async () => {
    mockDir.setContent(
      repositoryWithDependencies({ target: false, unrelatedVersion: '1.0.0' }),
    );
    const originalManifest = await fs.readFile(
      mockDir.resolve('package.json'),
      'utf8',
    );
    const originalLockfile = await fs.readFile(
      mockDir.resolve('yarn.lock'),
      'utf8',
    );

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install: async rootDir => {
          await fs.writeFile(
            path.join(rootDir, 'yarn.lock'),
            repositoryWithDependencies({
              target: true,
              unrelatedVersion: '1.1.0',
            })['yarn.lock'],
          );
        },
      }),
    ).resolves.toMatchObject({
      status: 'not-fixable',
      message: expect.stringContaining('unrelated lockfile changes'),
    });
    await expect(
      fs.readFile(mockDir.resolve('package.json'), 'utf8'),
    ).resolves.toBe(originalManifest);
    await expect(
      fs.readFile(mockDir.resolve('yarn.lock'), 'utf8'),
    ).resolves.toBe(originalLockfile);
  });

  it('does not retarget patches to older package versions', async () => {
    mockDir.setContent(repository({ target: true }));
    const originalManifest = await fs.readFile(
      mockDir.resolve('package.json'),
      'utf8',
    );
    const install = jest.fn();

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: async () =>
          new Response(
            JSON.stringify({
              releaseVersion: '1.0.1',
              packages: [
                { name: '@backstage/example', version: '1.0.0' },
                { name: '@backstage/other', version: '2.0.0' },
              ],
            }),
          ),
        install,
      }),
    ).resolves.toMatchObject({ status: 'not-fixable' });
    expect(install).not.toHaveBeenCalled();
    await expect(
      fs.readFile(mockDir.resolve('package.json'), 'utf8'),
    ).resolves.toBe(originalManifest);
  });

  it('restores project files when final verification fails', async () => {
    mockDir.setContent(repository());
    const originalManifest = await fs.readFile(
      mockDir.resolve('package.json'),
      'utf8',
    );
    const originalLockfile = await fs.readFile(
      mockDir.resolve('yarn.lock'),
      'utf8',
    );

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install: async rootDir => {
          await fs.writeFile(
            path.join(rootDir, 'yarn.lock'),
            repository({ target: true })['yarn.lock'],
          );
          await fs.rm(path.join(rootDir, '.yarn/patches/other.patch'));
        },
      }),
    ).resolves.toMatchObject({
      status: 'not-fixable',
      message: expect.stringContaining('did not pass patch verification'),
    });
    await expect(
      fs.readFile(mockDir.resolve('package.json'), 'utf8'),
    ).resolves.toBe(originalManifest);
    await expect(
      fs.readFile(mockDir.resolve('yarn.lock'), 'utf8'),
    ).resolves.toBe(originalLockfile);
  });

  it('reports when restoration leaves a partial repair', async () => {
    mockDir.setContent(repository());
    let writes = 0;

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
        install: async () => {
          throw new Error('install failed');
        },
        writeFile: async (filePath, content) => {
          writes += 1;
          if (writes === 2) {
            throw new Error('restore failed');
          }
          await fs.writeFile(filePath, content);
        },
      }),
    ).resolves.toMatchObject({
      status: 'not-fixable',
      message: expect.stringContaining(
        'project files may contain a partial repair',
      ),
    });
  });

  it('uses the repository Yarn configuration for repair', async () => {
    mockDir.setContent(repository());
    await fs.mkdir(mockDir.resolve('.yarn/releases'));
    await fs.writeFile(
      mockDir.resolve('.yarnrc.yml'),
      'yarnPath: .yarn/releases/test-yarn.cjs\n',
    );
    await fs.writeFile(
      mockDir.resolve('.yarn/releases/test-yarn.cjs'),
      `require('node:fs').writeFileSync('yarn.lock', ${JSON.stringify(
        repository({ target: true })['yarn.lock'],
      )});`,
    );

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
      }),
    ).resolves.toMatchObject({ status: 'fixed' });
  });

  it('restores project files when Yarn is terminated by a signal', async () => {
    mockDir.setContent(repository());
    const originalManifest = await fs.readFile(
      mockDir.resolve('package.json'),
      'utf8',
    );
    const originalLockfile = await fs.readFile(
      mockDir.resolve('yarn.lock'),
      'utf8',
    );
    await fs.mkdir(mockDir.resolve('.yarn/releases'));
    await fs.writeFile(
      mockDir.resolve('.yarnrc.yml'),
      'yarnPath: .yarn/releases/test-yarn.cjs\n',
    );
    await fs.writeFile(
      mockDir.resolve('.yarn/releases/test-yarn.cjs'),
      "process.kill(process.pid, 'SIGTERM');",
    );

    await expect(
      fixYarnPatches({
        rootDir: mockDir.path,
        fetch: fetchRelease,
      }),
    ).resolves.toMatchObject({
      status: 'not-fixable',
      message: expect.stringContaining('original project files were restored'),
    });
    await expect(
      fs.readFile(mockDir.resolve('package.json'), 'utf8'),
    ).resolves.toBe(originalManifest);
    await expect(
      fs.readFile(mockDir.resolve('yarn.lock'), 'utf8'),
    ).resolves.toBe(originalLockfile);
  });
});
