name: Cron
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

permissions: {}

jobs:
  cron:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Generate dependency merger token
        id: dependency-merger-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BACKSTAGE_DEPENDENCY_MERGER_CLIENT_ID }}
          private-key: ${{ secrets.BACKSTAGE_DEPENDENCY_MERGER_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
          permission-workflows: write

      - uses: backstage/actions/cron@a9e1b58ad52aaf319264e18c3ff6887a4c824b52 # v0.7.13
        with:
          app-id: ${{ secrets.BACKSTAGE_GOALIE_APPLICATION_ID }}
          private-key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
          installation-id: ${{ secrets.BACKSTAGE_GOALIE_INSTALLATION_ID }}
          merge-token: ${{ steps.dependency-merger-token.outputs.token }}
