name: Accessibility
on:
  # NOTE: If you change these you must update verify_accessibility-noop.yml as well
  pull_request:
    branches: [master]
    paths:
      - 'lighthouserc.js'
      - '.github/workflows/verify_accessibility.yml'
      - 'plugins/catalog/src/**'
      - 'plugins/catalog-react/src/**'
      - 'plugins/techdocs/src/**'
      - 'plugins/techdocs-react/src/**'
      - 'plugins/scaffolder/src/**'
      - 'plugins/scaffolder-react/src/**'
      - 'plugins/search/src/**'
      - 'plugins/search-react/src/**'
jobs:
  lhci:
    name: Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js 22.x
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22.x
      - name: yarn install
        uses: backstage/actions/yarn-install@2cd6978b476cbdc39fec48346f8b6ca13199dd6a # v0.7.8
        with:
          cache-prefix: ${{ runner.os }}-v22.x
      - name: run Lighthouse CI
        run: |
          yarn dlx @lhci/cli@0.11.x autorun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
