name: E2E Techdocs
on:
  pull_request:
    paths:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-techdocs.yml'
      - 'packages/techdocs-cli/**'
      - 'packages/techdocs-cli-embedded-app/**'
      - 'plugins/techdocs/**'
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  verify:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=4096 --experimental-vm-modules

    name: Techdocs
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.9'

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node-version == '24.x' && '24.19.0' || matrix.node-version }}
      - name: yarn install
        uses: backstage/actions/yarn-install@a9e1b58ad52aaf319264e18c3ff6887a4c824b52 # v0.7.13
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: build techdocs-cli
        working-directory: packages/techdocs-cli
        run: yarn build

      - name: Install mkdocs & techdocs-core
        run: python -m pip install mkdocs-techdocs-core==1.1.7 mkdocs==1.4.0

      - name: techdocs-cli e2e test
        working-directory: packages/techdocs-cli
        run: yarn test:e2e:ci
        env:
          BACKSTAGE_TEST_DISABLE_DOCKER: 1
