# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: Microsite Void
on:
  pull_request:
    paths-ignore:
      - '.github/workflows/verify_microsite.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'mkdocs-ci.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest

    name: Microsite
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - run: echo NOOP
