name: Chromatic
on:
  # NOTE: If you change these you must update verify_storybook-noop.yml as well
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/verify_chromatic.yml'
      - '.storybook/**'
      - 'packages/ui/**'
      - '**/*.stories.tsx'

jobs:
  chromatic:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]

    name: Chromatic
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0 # Required to retrieve git history
          filter: blob:none

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: Install dependencies
        uses: backstage/actions/yarn-install@2cd6978b476cbdc39fec48346f8b6ca13199dd6a # v0.7.8
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Build Storybook
        run: yarn build-storybook:chromatic

      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@14cfaef73576e69f95f47f60058063f46ca38719 # latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # projectToken intentionally shared to allow collaborators to run Chromatic on forks
          # https://www.chromatic.com/docs/custom-ci-provider#run-chromatic-on-external-forks-of-open-source-projects
          projectToken: chpt_dab72dc0f97d55b
          storybookBuildDir: dist-storybook
          autoAcceptChanges: master
          onlyChanged: true
          externals: |
            packages/ui/**/*.css
            packages/ui/css/**
            packages/ui/src/**/*.css

      - name: Prepare Chromatic Message
        env:
          CHROMATIC_BUILD_URL: ${{ steps.chromatic.outputs.buildUrl }}
          CHROMATIC_CHANGE_COUNT: ${{ steps.chromatic.outputs.changeCount }}
        if: github.event_name == 'pull_request' && steps.chromatic.outputs.url
        id: prepareMessage
        run: |
          if [ "$CHROMATIC_CHANGE_COUNT" = "0" ] || [ -z "$CHROMATIC_CHANGE_COUNT" ]; then
            text="No visual changes detected - [**View build in Chromatic**]($CHROMATIC_BUILD_URL)"
          else
            text="**$CHROMATIC_CHANGE_COUNT** visual changes are waiting for review - [**Review changes in Chromatic**]($CHROMATIC_BUILD_URL)"
          fi

          echo "changes-text=$text" >> "$GITHUB_OUTPUT"

      - name: Post Chromatic Results to Job Summary
        env:
          CHANGES_TEXT: ${{ steps.prepareMessage.outputs.changes-text }}
          CHROMATIC_COMPONENT_COUNT: ${{ steps.chromatic.outputs.componentCount }}
          CHROMATIC_SPEC_COUNT: ${{ steps.chromatic.outputs.specCount }}
          CHROMATIC_STORYBOOK_URL: ${{ steps.chromatic.outputs.storybookUrl }}
        if: github.event_name == 'pull_request' && steps.chromatic.outputs.url
        run: |
          cat << EOF >> "$GITHUB_STEP_SUMMARY"
          ## 🎨 Visual Testing with Chromatic

          - $CHANGES_TEXT
          - **$CHROMATIC_SPEC_COUNT** stories for **$CHROMATIC_COMPONENT_COUNT** Components - [**Preview changes in Storybook**]($CHROMATIC_STORYBOOK_URL)
          EOF

      - name: Post Chromatic Link in PR Comment
        if: github.event_name == 'pull_request' && steps.chromatic.outputs.url && github.event.pull_request.head.repo.full_name == github.repository
        uses: mshick/add-pr-comment@ec328af66588ab8f77cdeb2c264f14aba45bbf59 # v3
        with:
          message: |
            ## 🎨 Visual Testing with Chromatic

            - ${{ steps.prepareMessage.outputs.changes-text }}
            - **${{ steps.chromatic.outputs.specCount}}** stories for **${{ steps.chromatic.outputs.componentCount}}** Components - [**Preview changes in Storybook**](${{ steps.chromatic.outputs.storybookUrl }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}
