name: Accessibility
on:
  # NOTE: If you change these you must update verify_accessibility-noop.yml as well
  pull_request:
    branches: [master]
    paths:
      - 'lighthouserc.js'
      - '.github/workflows/verify_accessibility.yml'
      - 'plugins/catalog/src/**'
      - 'plugins/catalog-react/src/**'
      - 'plugins/techdocs/src/**'
      - 'plugins/techdocs-react/src/**'
      - 'plugins/scaffolder/src/**'
      - 'plugins/scaffolder-react/src/**'
      - 'plugins/search/src/**'
      - 'plugins/search-react/src/**'
jobs:
  lhci:
    name: Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Use Node.js 22.x
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 22.x
      - name: yarn install
        uses: backstage/actions/yarn-install@a9e1b58ad52aaf319264e18c3ff6887a4c824b52 # v0.7.13
        with:
          cache-prefix: ${{ runner.os }}-v22.x
      - name: run Lighthouse CI
        run: |
          yarn dlx @lhci/cli@0.11.x autorun
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
