# NO-OP placeholder that always passes for other paths
# This is here so that we're able to set the status check as required

name: E2E Windows Void
on:
  pull_request:
    paths-ignore:
      - 'yarn.lock'
      - '.github/workflows/verify_e2e-windows.yml'
      - 'packages/cli/**'
      - 'packages/e2e-test/**'
      - 'packages/create-app/**'

permissions: {}

jobs:
  noop:
    runs-on: windows-2025

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    name: E2E Windows ${{ matrix.node-version }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - run: echo NOOP
